Update create account script
uabrc/rabbitmq_agents pull request #33
Opened 2020-04-28 22:49 UTC by diedpigs

use `argparse` library to take command line arguments
implement its own callback function for rabbitmq
update `consume` function in `rc_util` to take `routing_key` as argument

I was going to modify `worker` in `rc_util`, I think it is considered an example and is designed for dev environment. Therefore, I modify `create_account.py` instead.

All feedback are welcome.

2020-05-08 01:52 UTC, eesaanatluri requested changes

2020-05-08 01:52 UTC, eesaanatluri commented on create_account.py
Just missing these imports
```
import json
import rc_rmq
```

2020-05-12 16:18 UTC, diedpigs commented on create_account.py
Should be fixed in 079f5e6

2020-09-25 20:13 UTC, rtripath89 commented
Please check the merge conflict

2020-10-13 20:26 UTC, merged